### ISSUE TITLE
Desenvolvimento da Seção de Instalação e Configuração do Flutter

### ISSUE THREAD

**Issue by lucasvarino** [feliper2002/flutter4noobs#2]
Boa tarde, 

Já existe alguém escrevendo algo sobre a seção de Instalação e Configuração do Flutter nos OS? Caso não haja, posso ajudar contribuindo para a seção do Windows e do Linux, que são os sistemas operacionais que instalei e utilizei o Flutter.

**Comment by feliper2002** [comment]
Opa! Pode escrever sim, vai ajudar demais. Bom dia!
